version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    depends_on:
      - nginx
    restart: always
  
  nextcloud:  
    container_name: nextcloud
    image: nextcloud
    depends_on:
      - mysql
      - nginx
    restart: always
      
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    depends_on:
      - nginx
    restart: always
    
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    
  dnsmasq:
    container_name: dnsmasq
    image: storytel/dnsmasq
    cap_drop:
      - NET_ADMIN
    depends_on:
      - nginx
    restart: always
  
  emby:
    container_name: emby
    image: emby/embyserver
    restart: always
    
  portainer:
    container_name: portainer
    image: portainer/portainer
    depends_on:
      - ddclient
      - nginx
      - nextcloud
      - mysql
      - emby
    restart: always
