version: "3"
services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
    restart: always
    
  nginx:
      container_name: nginx
      image: xataz/nginx
      ports:
        - "80:8080"
        - "443:8443"
      volumes:
        - /var/log/nginx:/log
        - /opt/dockers/nginx/conf:/nginx/conf
        - /opt/dockers/nginx/site-enable:/sites-enabled
      restart: always
      
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /opt/dockers/portainer:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  


