version: "3"
services:
  database:
    container_name: mysql
    image: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always
  
  application:  
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - /opt/dockers/nextcloud/data:/var/www/html/data
      - /opt/dockers/nextcloud/config:/var/www/html/config
      - /opt/dockers/nextcloud/apps:/var/www/html/apps
    depends_on:
      - database
      - web
      - network
    restart: always
      
  network:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
    restart: always
    
  web:
      container_name: nginx
      image: xataz/nginx
      ports:
        - "80:8080"
      volumes:
        - /var/log/nginx:/log
        - /opt/dockers/nginx/conf:/nginx/conf
        - /opt/dockers/nginx/site-enable:/sites-enabled
      restart: always
      
  maintenance:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /opt/dockers/portainer:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
