version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    depends_on:
      - nginx
    networks:
      - back-network
    restart: always
  
  nextcloud:  
    container_name: nextcloud
    image: nextcloud
    depends_on:
      - mysql
      - ddclient
      - nginx
    networks:
      - back-network
    restart: always
      
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    depends_on:
      - dnsmasq
    networks:
      - back-network
    restart: always
    
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - ddclient
    networks:
      - front-network
      - back-network
    restart: always
    
  dnsmasq:
    container_name: dnsmasq
    image: storytel/dnsmasq
    cap_drop:
      - NET_ADMIN
    networks:
      - front-network
      - back-network
    restart: always
    
  portainer:
    container_name: portainer
    image: portainer/portainer
    depends_on:
      - ddclient
      - nginx
      - nextcloud
      - mysql
    networks:
      - front-network
      - back-network
    restart: always
    
 networks:
   front-network:
     driver: host
   back-network:
     driver: host
