# Docker-compose file pour l'environnement de développement/test
version: "3"
services:
  mysql:
    ports:
      - "3306:3306"
    volumes:
      - /var/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud_dev

  nextcloud:
    ports:
      - "8080:80"
    volumes:
      - /var/nextcloud/data:/var/www/html/data
      - /var/nextcloud/config:/var/www/html/config
      - /var/nextcloud/apps:/var/www/html/apps

  ddclient:
    volumes:
      - /var/ddclient/config:/config

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/nginx/conf.d:/etc/nginx/conf.d
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf
      
  dnsmasq:
    volumes:
      - /var/dnsmasq:/etc/dnsmasq
    
  emby:
    ports:
      - "8096:8096"
    volumes:
      - /var/emby/config:/config
      - /var/emby/data:/mnt/share1
    environment:
      - UID=105
      - GID=100
      - GIDLISt=100

  portainer:
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer/data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock

