version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    depends_on:
      - nginx
    restart: always
  
  netxcloud:  
    container_name: nextcloud
    image: nextcloud
    depends_on:
      - mysql
      - ddclient
      - nginx
    restart: always
      
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    depends_on:
      - dnsmasq
    restart: always
    
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - ddclient
    restart: always
    
  dnsmasq:
    container_name: dnsmasq
    image: storytel/dnsmasq
    cap_drop:
      - NET_ADMIN
    restart: always
    
  portainer:
    container_name: portainer
    image: portainer/portainer
    depends_on:
      - ddclient
      - nginx
      - netxcloud
      - mysql
    restart: always
    
