version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/mysql:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
    restart: always
  
  app:  
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - /var/nextcloud/data:/var/www/html/data
      - /opt/dockers/nextcloud/config:/var/www/html/config
      - /var/nextcloud/apps:/var/www/html/apps
    depends_on:
      - database
    restart: always
      
  net:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
    restart: always
    
  web:
      container_name: nginx
      image: xataz/nginx
      ports:
        - "80:8080"
      volumes:
        - /var/log/nginx:/log
        - /opt/dockers/nginx/conf:/nginx/conf
        - /opt/dockers/nginx/site-enable:/sites-enabled
      restart: always
      
  mnt:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /opt/dockers/portainer:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
