version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test 
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=test 
      - MYSQL_PASSWORD=test
    depends_on:
      - nginx
    restart: always
  
  netxcloud:  
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - /var/nextcloud/data:/var/www/html/data
      - /var/nextcloud/config:/var/www/html/config
      - /var/nextcloud/apps:/var/www/html/apps
    depends_on:
      - mysql
      - ddclient
      - nginx
    restart: always
      
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - TZ="Europe/Paris"
    volumes:
      - /var/ddclient/config:/config
    depends_on
      - dnsmasq
    restart: always
    
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /var/nginx/conf.d:/etc/nginx/conf.d
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ddclient
    restart: always
    
  dnsmasq:
    container_name: dnsmasq
    image: jpillora/dnsmasq
    ports:
      - "53:53"
    volumes:
      - /var/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf 
      - /etc/resolv.conf:/etc/resolv.conf 
      - /etc/hosts:/etc/hosts
    restart: always
    
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer/data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - ddclient
      - nginx
      - netxcloud
      - mysql
    restart: always
    
