version: "3"
services:
  nginx:
      container_name: nginx
      image: xataz/nginx
      ports:
        - "80:8080"
        - "443:8443"
      environment:
            - GID=1000
            - UID=1000
      volumes:
        - /var/log/nginx:/log
        - /opt/dockers/nginx/conf:/nginx/conf
        - /opt/dockers/nginx/site-enable:/sites-enabled
      depends_on:
        - ddclient
        - portainer
      restart: always
      
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /opt/dockers/portainer:/data portainer/portainer
      - /opt/dockers/nginx/conf:/nginx/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - PGID=1001
      - PUID=1001
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
    restart: always


