version: "3"
services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - PGID=1000
      - PUID=1000
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
      - /var/log/ddclient:/var/log/ddclient
