version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test 
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=test 
      - MYSQL_PASSWORD=test
    depends_on:
      - web
    restart: always
  
  app:  
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - /var/nextcloud/data:/var/www/html/data
      - /var/nextcloud/config:/var/www/html/config
      - /var/nextcloud/apps:/var/www/html/apps
    depends_on:
      - db
      - net
      - web
    restart: always
      
  net:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      - TZ="Europe/Paris"
    volumes:
      - /opt/dockers/ddclient/config:/config
    restart: always
    
  web:
    container_name: nginx
    image: xataz/nginx
    ports:
      - "80:8080"
    volumes:
      - /var/log/nginx:/nginx/log
      - /var/nginx/conf/sites-enabled:/nginx/sites-enabled
      - /var/nginx/conf/nginx.conf:/nginx/conf/nginx.conf
    depends_on:
      - net
    restart: always
      
  maint:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer/data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - net
      - web
      - app
      - db
    restart: always
    
